### Numpy practice

In [39]:
import numpy as np
array = np.array([2,3,3,3,2])
a = np.array([[1, 2,4],[2, 35,32]])
b = np.array([[2, 3,5],[2, 5,3]])
print(array[1: 3])
print(a[1,1])
print(a+b)
print(a*b)
print(a**b)
print(a.mean())
print(a.max())
print(a.min())
print(a.std())

[3 3]
35
[[ 3  5  9]
 [ 4 40 35]]
[[  2   6  20]
 [  4 175  96]]
[[       1        8     1024]
 [       4 52521875    32768]]
12.666666666666666
35
1
14.783624574357791


In [17]:
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.arange(2,5,3))
print(np.linspace(0, 1, 5))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[2]
[0.   0.25 0.5  0.75 1.  ]


#### Problem 1:

###### Create a 1D array of numbers from 1 to 10, square each value, then find the average.

In [30]:
a = np.array([1, 2,3,4,5,6,7,8,9,10])
print("array =", a)
print("square of each value= ", a**2)
print("average = ", np.average(a))

array = [ 1  2  3  4  5  6  7  8  9 10]
square of each value=  [  1   4   9  16  25  36  49  64  81 100]
average =  5.5


#### Problem 2:

###### Simulate 100 dice rolls (values from 1–6), then count how many times each number occurred.

In [47]:
rolls = np.random.randint(1,7, size=100)
print(rolls)
(unique, counts) = np.unique(rolls, return_counts=True)
results = {int(k): int(v) for k, v in zip(unique, counts)}
print(results)


[3 3 1 4 3 2 6 3 5 3 2 1 6 6 1 5 3 1 1 1 6 6 5 5 6 2 5 2 2 1 3 1 5 6 6 2 2
 2 6 1 6 6 1 6 6 6 4 5 4 6 3 3 3 2 3 3 5 2 6 4 2 5 2 6 1 2 3 4 3 6 6 1 4 6
 1 3 6 6 3 6 4 2 5 5 4 4 4 4 1 6 3 5 6 4 5 2 5 3 2 3]
{1: 14, 2: 16, 3: 19, 4: 12, 5: 14, 6: 25}
